// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 2AA4Assignment1.CatanModel;



/************************************************************/
/**
 * 
 */
public class Board {
				/**
				 * 
				 */
				private List tiles;
				/**
				 * 
				 */
				private List intersections;
				/**
				 * 
				 */
				private List edges;
				/**
				 * 
				 */
				public Tile[] tile;
				/**
				 * 
				 */
				public Edge[] edge;
				/**
				 * 
				 */
				public Intersection[] intersection;
	/**
	 * 
	 * @param p 
	 * @param e 
	 * @return 
	 */
	public boolean BuildRoad(Player p, Edge e) {
	}
	/**
	 * 
	 * @param p 
	 * @param i 
	 * @return 
	 */
	public boolean buildSettlement(Player p, Intersection i) {
	}
	/**
	 * 
	 * @param p 
	 * @param i 
	 * @return 
	 */
	public boolean buildCity(Player p, Intersection i) {
	}
}
