// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 2AA4Assignment1.CatanModel;



/************************************************************/
/**
 * 
 */
public interface Dice {
	/**
	 * 
	 * @return 
	 */
	public int roll() ;
}
