// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 2AA4Assignment1.CatanModel;



/************************************************************/
/**
 * 
 */
public class Edge {
				/**
				 * 
				 */
				private int edgeID;
				/**
				 * 
				 */
				public Intersection[] intersection;
}
