// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 2AA4Assignment1.CatanModel;



/************************************************************/
/**
 * 
 */
public class Game {
				/**
				 * 
				 */
				private int currentRound;
				/**
				 * 
				 */
				private int maxRound;
				/**
				 * 
				 */
				public Board board;
				/**
				 * 
				 */
				public Player[] player;
				/**
				 * 
				 */
				public Resources resources;
	/**
	 * 
	 */
	public void start() {
	}
	/**
	 * 
	 * @return 
	 */
	public boolean checkWinner() {
	}
	/**
	 * 
	 */
	public void playRound() {
	}
	/**
	 * 
	 */
	public void endGame() {
	}
}
