// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 2AA4Assignment1.CatanModel;



/************************************************************/
/**
 * 
 */
public class Intersection {
				/**
				 * 
				 */
				private List edges;
				/**
				 * 
				 */
				private List tiles;
				/**
				 * 
				 */
				private Player owner;
				/**
				 * 
				 */
				private boolean isCity;
}
