// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 2AA4Assignment1.CatanModel;



/************************************************************/
/**
 * 
 */
public class MultiDice implements Dice
 {
				/**
				 * 
				 */
				public List dice;
				/**
				 * 
				 */
				public RegularDice regulardice;
	/**
	 * 
	 */
	public void MultiDice() {
	}
	/**
	 * 
	 * @return 
	 */
	public int roll() {
	}
}
