// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 2AA4Assignment1.CatanModel;



/************************************************************/
/**
 * 
 */
public class Player {
				/**
				 * 
				 */
				private int roadsBuilt;
				/**
				 * 
				 */
				private int citiesBuilt;
				/**
				 * 
				 */
				private int settlementsBuilt;
				/**
				 * 
				 */
				private boolean longestRoad;
				/**
				 * 
				 */
				private boolean longestArmy;
				/**
				 * 
				 */
				private int age;
				/**
				 * 
				 */
				private int vPoints;
				/**
				 * 
				 */
				private Map resources;
				/**
				 * 
				 */
				private List roads;
				/**
				 * 
				 */
				private List settlements;
				/**
				 * 
				 */
				public Edge edge;
				/**
				 * 
				 */
				public Intersection intersection;
				/**
				 * 
				 */
				public Resources resources;
	/**
	 * 
	 * @return 
	 */
	public int getRoadsBuilt() {
	}
	/**
	 * 
	 * @return 
	 */
	public int getCitiesBuilt() {
	}
	/**
	 * 
	 * @return 
	 */
	public int getSettlementsBuilt() {
	}
	/**
	 * 
	 * @return 
	 */
	public boolean hasLongestRoad() {
	}
	/**
	 * 
	 * @return 
	 */
	public boolean hasLargestArmy() {
	}
	/**
	 * 
	 * @return 
	 */
	public int getAge() {
	}
	/**
	 * 
	 * @return 
	 */
	public int getVictoryPoints() {
	}
	/**
	 * 
	 * @return 
	 */
	public Map getResources() {
	}
	/**
	 * 
	 * @return 
	 */
	public List getRoads() {
	}
	/**
	 * 
	 * @return 
	 */
	public List getSettlements() {
	}
}
