// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 2AA4Assignment1.CatanModel;



/************************************************************/
/**
 * 
 */
public class RegularDice implements Dice
 {
				/**
				 * 
				 */
				public int sides;
	/**
	 * 
	 * @param sides 
	 */
	public void RegularDice(int sides) {
	}
	/**
	 * 
	 * @return 
	 */
	public int roll() {
	}
}
