// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 2AA4Assignment1.CatanModel;



/************************************************************/
/**
 * 
 */
public enum Resource {
	/**
	 * 
	 */
	WOOL,
	/**
	 * 
	 */
	ORE,
	/**
	 * 
	 */
	BRICK,
	/**
	 * 
	 */
	LUMBER,
	/**
	 * 
	 */
	GRAIN,
	/**
	 * 
	 */
	WOOL,
	/**
	 * 
	 */
	ORE,
	/**
	 * 
	 */
	BRICK,
	/**
	 * 
	 */
	LUMBER,
	/**
	 * 
	 */
	GRAIN
	;
}
