// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 2AA4Assignment1.CatanModel;



/************************************************************/
/**
 * 
 */
public class Resources {
				/**
				 * 
				 */
				private Map resourceCounts;
	/**
	 * 
	 * @param initial 
	 */
	public void Resources(Map initial) {
	}
	/**
	 * 
	 * @param n 
	 * @param p 
	 * @param r 
	 * @return 
	 */
	public boolean giveResources(int n, Player p, Resource r) {
	}
	/**
	 * 
	 */
	public void spendResources() {
	}
}
