// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 2AA4Assignment1.CatanModel;



/************************************************************/
/**
 * 
 */
public class ResourceProduction {
				/**
				 * 
				 */
				private undef dice1;
				/**
				 * 
				 */
				private undef dice2;
				/**
				 * 
				 */
				public Dice dice;
	/**
	 * 
	 * @param p1 
	 * @param p2 
	 * @param p3 
	 * @param p4 
	 * @return 
	 */
	public boolean produce(Player p1, Player p2, Player p3, Player p4) {
	}
}
