// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 2 AA4Assignment1.CatanModel;

/************************************************************/
/**
 * 
 */
public class Special Card
{

	/**
	 * 
	 * @return 
	 * @param p 
	 */
	public Player largestArmy(Player p) {
	}

	/**
	 * 
	 * @return 
	 * @param p 
	 */
	public Player longestRoad(Player p) {
	}
}
