// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 2AA4Assignment1.CatanModel;



/************************************************************/
/**
 * 
 */
public enum Terrain {
	/**
	 * 
	 */
	MOUNTAIN,
	/**
	 * 
	 */
	FOREST,
	/**
	 * 
	 */
	HILLS,
	/**
	 * 
	 */
	FIELDS,
	/**
	 * 
	 */
	PASTURE,
	/**
	 * 
	 */
	DESERT
	;
}
