// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 2AA4Assignment1.CatanModel;



/************************************************************/
/**
 * 
 */
public class Tile {
				/**
				 * 
				 */
				private List intersections;
				/**
				 * 
				 */
				private int token;
				/**
				 * 
				 */
				private int tileID;
				/**
				 * 
				 */
				public Intersection[] intersection;
	/**
	 * 
	 * @param t 
	 * @return 
	 */
	public Resource getResource(Terrain t) {
	}
}
